name: Build and test

on:
  push:
    branch: [ "main" ]
    paths-ignore:
      - "**.md"
    workflow_dispatch: { }

jobs:
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Cancel previous build
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Assemble Debug
        run: bash ./gradlew assembleDebug

      - name: Upload  Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/**.apk

