name: Build and Test

on:
  push:
    branch: [ "main" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branch: [ "main" ]
    paths-ignore:
      - "**.md"
  workflow_dispatch: { }

jobs:
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous build
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Restore gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Assemble Debug
        run: bash ./gradlew assembleDebug
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: dairybook
          path: app/build/outputs/apk/debug/**.apk

